[package]
name = "bin"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib = { path = "../lib" }
dotenv = "0.15"
log = "0.4"
log4rs = { version = "1", features = ["toml_format"] }
chrono = "0.4"
tokio = { features = ["macros", "rt-multi-thread", "sync"], version = "1" }
