stages:
  - build
  - build static binary

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker version
    - export LOWER_CASE_CI_PROJECT_NAME=$(echo "$CI_PROJECT_NAME" | tr '[:upper:]' '[:lower:]')
    - DOCKER_BUILDKIT=1 docker build --progress=plain -t bitsfitr/$LOWER_CASE_CI_PROJECT_NAME:latest -t bitsfitr/$LOWER_CASE_CI_PROJECT_NAME:$CI_COMMIT_REF_NAME .
    - docker login -u bitsfitr -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push --all-tags bitsfitr/$LOWER_CASE_CI_PROJECT_NAME
    - docker logout

build_static_binary:
  stage: build static binary
  cache:
    - key:
        files:
          - Cargo.lock
      paths:
        - target/
  image: ekidd/rust-musl-builder:latest
  script:
    - cargo --version && rustc --version
    - cargo build --release
  artifacts:
    paths:
      - target/release/bin
