stages:
  - build

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker version
    - DOCKER_BUILDKIT=1 docker build --progress=plain -t bitsfitr/rsbot:latest .
    - docker login -u bitsfitr -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push bitsfitr/rsbot:latest
    - docker logout
