stages:
  - build

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

build:
  image: "rust:stretch"
  before_script:
    - apt-get update -qq && apt-get upgrade -y -qq && apt-get install -y -qq libssl-dev pkg-config libsqlite3-dev clang
    - apt-get -y -qq remove libsodium-dev
    - threads=$(cat /proc/cpuinfo | awk '/^processor/{print $3}' | wc -l)
    - git clone https://github.com/jedisct1/libsodium -b stable && cd libsodium && ./autogen.sh && ./configure && make -j$threads && make install
    - cargo --version
    - rustc --version
    - cargo update
  stage: build
  script:
    - cargo build --release
  cache:
    untracked: true
    paths:
      - target/
      - cargo/
  artifacts:
    paths:
      - config/config_example.toml
      - assets/bttv_emotes.json
      - target/release/rsbot
