stages:
  - audit
  - build static binary

audit:
  stage: audit
  image: bitsfitr/rust-musl-builder
  script:
    - cargo audit

build_static_binary:
  stage: build static binary
  image: docker:latest
  services:
    - docker:dind
  cache:
    - key:
        files:
          - Cargo.lock
      untracked: true
      paths:
        - cargo-registry/
        - cargo-git/
        - target/
  script:
    - docker version
    - docker run --rm bitsfitr/rust-musl-builder cargo --version
    - docker run --rm bitsfitr/rust-musl-builder rustc --version
    - mkdir -p cargo-registry && mkdir -p cargo-git
    - docker run --rm -v "$(pwd)":/home/rust/src -v `pwd`/cargo-registry:/home/rust/.cargo/registry -v `pwd`/cargo-git:/home/rust/.cargo/git bitsfitr/rust-musl-builder sudo chown -R rust:rust /home/rust
    - docker run --rm -v "$(pwd)":/home/rust/src -v `pwd`/cargo-registry:/home/rust/.cargo/registry -v `pwd`/cargo-git:/home/rust/.cargo/git bitsfitr/rust-musl-builder cargo build --release
    - rm .dockerignore
    - export LOWER_CASE_CI_PROJECT_NAME=$(echo "$CI_PROJECT_NAME" | tr '[:upper:]' '[:lower:]')
    - DOCKER_BUILDKIT=1 docker build --progress=plain -t bitsfitr/$LOWER_CASE_CI_PROJECT_NAME:latest -t bitsfitr/$LOWER_CASE_CI_PROJECT_NAME:$CI_COMMIT_REF_NAME -f Dockerfile.gitlab .
    - docker login -u bitsfitr -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push --all-tags bitsfitr/$LOWER_CASE_CI_PROJECT_NAME
    - docker logout
  artifacts:
    paths:
      - ./target/x86_64-unknown-linux-musl/release/bin
