stages:
  - build

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

build:
  image: "htli/rust-nightly"
  before_script:
    - apt-get update -qq && apt-get install -y -qq libssl-dev pkg-config libsqlite3-dev libsodium-dev clang
    - cargo --version
    - rustc --version
    - cargo update
  stage: build
  script:
    - cargo build --release
  cache:
    untracked: true
    paths:
      - target/
      - cargo/
  artifacts:
    paths:
      - config/config_example.toml
      - assets/bttv_emotes.json
      - target/release/rsbot
