[package]
name = "rsbot"
version = "0.1.0"
authors = ["raymond.mao","daniel.holzner"]

[dependencies]
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
log = "0.3"
chrono = "0.4"

[dependencies.serenity]
git = "https://github.com/zeyla/serenity.git"
features = ["cache", "framework", "standard_framework"]