[package]
name = "rsbot"
version = "0.2.0"
authors = ["raymond.mao","daniel.holzner"]

[dependencies]
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
log = "0.3"
typemap = "0.3"
chrono = { version = "0.4", features = ["serde", "rustc-serialize"] }

[dependencies.serenity]
git = "https://github.com/zeyla/serenity.git"
features = ["cache", "framework", "standard_framework", "voice"]