[workspace]
members = [
    "rsbot",
	"rsbot_lib"
]

[profile.release]
lto = "thin"
codegen-units = 1
debuginfo = 0
opt-level = 3

[patch.crates-io]
openssl = { git = "https://github.com/ishitatsuyuki/rust-openssl", branch = "0.9.x" }