[package]
name = "rsbot"
version = "0.1.0"
authors = ["raymond.mao"]

[dependencies]
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
typemap = "0.3"

[dependencies.serenity]
git = "https://github.com/zeyla/serenity.git"
features = ["framework", "standard_framework"]