version: '3.9'
services:
    lavalink:
        image: fredboat/lavalink:master
        restart: always
        init: true
        environment:
            LAVALINK_SERVER_PASSWORD: youshallnotpass
            SERVER_PORT: 2333
            SERVER_HOST: 0.0.0.0
    rsbot:
        image: bitsfitr/krabot:main
        restart: always
        env_file: 
            - ./.env.docker
        depends_on: 
            - lavalink
