[package]
name = "rsbot_lib"
version = "0.0.0"
authors = ["raymond.mao","daniel.holzner"]
publish = false

[dependencies]
diesel = { version = "1.4", features = ["postgres", "uuid", "r2d2", "serde_json", "chrono"] }
diesel_migrations = "1.4"
dotenv = "*"
log = "*"
serde_json = "1"
chrono = "*"