[required]
token = "lorem_ipsum_token_insert_here"
prefix = "!"
mention = true #should the bot react on mention?
shards = 1
sqlite_path = "./db/"

[optional]
#database_name = "" # defaults to rsbot.db if nothing is entered
youtube_token = ""
setting = true